# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from uservice_market_app1.rpc import app1_pb2 as uservice__market__app1_dot_rpc_dot_app1__pb2


class PingServiceStub(object):
    """Definicja serwisu Ping
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/PingService/ping',
                request_serializer=uservice__market__app1_dot_rpc_dot_app1__pb2.PingRequest.SerializeToString,
                response_deserializer=uservice__market__app1_dot_rpc_dot_app1__pb2.PingResponse.FromString,
                )


class PingServiceServicer(object):
    """Definicja serwisu Ping
    """

    def ping(self, request, context):
        """Metoda ping, przyjmująca żądanie PingRequest i zwracająca odpowiedź PingResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=uservice__market__app1_dot_rpc_dot_app1__pb2.PingRequest.FromString,
                    response_serializer=uservice__market__app1_dot_rpc_dot_app1__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PingService(object):
    """Definicja serwisu Ping
    """

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PingService/ping',
            uservice__market__app1_dot_rpc_dot_app1__pb2.PingRequest.SerializeToString,
            uservice__market__app1_dot_rpc_dot_app1__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
