spring:
  application:
    name: webapi
  main:
    banner-mode: off
  jmx:
    enabled: false
  # required to enable websockets on GQL subscriptions
  graphql.websocket.path: /graphql
  threads.virtual.enabled: true

logging.level: 
  '[org.apache.kafka]': warn


# https://netflix.github.io/dgs/advanced/virtual-threads/#virtual-threads-jdk-21
dgs.graphql.virtualthreads.enabled: true


spring.kafka:
  producer:
    bootstrap-servers: PLAINTEXT://kafka.default.svc.cluster.local:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  consumer:
    bootstrap-servers: PLAINTEXT://kafka.default.svc.cluster.local:9092
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    group-id: moja-grupa-ccc
    auto-offset-reset: latest
    value-deserializer.specific.avro.reader: true
    specific.avro.reader: true
    properties:
      specific.avro.reader: true        
  properties:
    schema.registry.url: http://schema-registry-for-avro.default.svc.cluster.local:8081
