spring:
  application:
    name: webapi
  main:
    banner-mode: off
  jmx:
    enabled: false
  # required to enable websockets on GQL subscriptions
  graphql.websocket.path: /graphql
  threads.virtual.enabled: true

logging.level: 
  '[org.apache.kafka]': info


# https://netflix.github.io/dgs/advanced/virtual-threads/#virtual-threads-jdk-21
dgs.graphql.virtualthreads.enabled: true


