# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_rpc/agent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61gent_rpc/agent.proto\" \n\rMyPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eMyPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t21\n\x04Ping\x12)\n\x04ping\x12\x0e.MyPingRequest\x1a\x0f.MyPingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_rpc.agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MYPINGREQUEST']._serialized_start=25
  _globals['_MYPINGREQUEST']._serialized_end=57
  _globals['_MYPINGRESPONSE']._serialized_start=59
  _globals['_MYPINGRESPONSE']._serialized_end=92
  _globals['_PING']._serialized_start=94
  _globals['_PING']._serialized_end=143
# @@protoc_insertion_point(module_scope)
