name: Deploy Dev Environment

on:
  push:
    branches:
      - dev
    paths:
      - 'webapp/**'
      - 'infra/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://dev.investpulse.net
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json
      
      - name: Build & Prepare Static Assets
        run: ./scripts/build_and_push.sh dev
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"
      
      - name: Deploy Infrastructure with Terraform
        run: ./scripts/deploy.sh dev
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/webapp"
          api_location: ""
          output_location: "out"
      
      - name: Deployment Summary
        run: |
          echo "✅ Dev environment deployment completed!"
          echo "🌐 URL: https://dev.investpulse.net"
          echo "📦 Environment: dev"
          echo "🔗 Static Web App URL: ${{ steps.deploy.outputs.static_web_app_url }}"